development: 
  cloud_name: <%= Rails.application.credentials.cloudinary_development[:cloud_name] %>
  api_key: <%= Rails.application.credentials.cloudinary_development[:api_key] %>
  api_secret: <%= Rails.application.credentials.cloudinary_development[:api_secret] %>
  secure: true

production:
  cloud_name: <%= Rails.application.credentials.cloudinary_production[:cloud_name] %>
  api_key: <%= Rails.application.credentials.cloudinary_production[:api_key] %>
  api_secret: <%= Rails.application.credentials.cloudinary_production[:api_secret] %>
  secure: true