test: &default

  # Credentials for REST APIs
  client_id: <%= Rails.application.credentials.paypal[:client_id] %>
  client_secret: <%= Rails.application.credentials.paypal[:secret_key] %>

  # Mode can be 'live' or 'sandbox'
  mode: sandbox


development:
  <<: *default

production:
  <<: *default
  mode: live
